version: '3.8'

services:
  poke-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poke-api
    ports:
      - "8128:8128"
    volumes:
      - ./logs/log.txt:/app/logs/log.txt
    networks:
      - public-network
    image: poke-api:latest

  analyser:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    container_name: analyser
    volumes:
      - ./logs:/logs
    network_mode: none
    image: analyser:latest

# You don't need this as bridge is the default driver
networks:
  public-network:
    driver: bridge
