apiVersion: apps/v1
kind: Deployment
metadata:
  name: gottafetchthemall
  labels:
    app: poke-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poke-api
  template:
    metadata:
      labels:
        app: poke-api
    spec:
      containers:
      - name: gottafetchthemall
        image: 794038210581.dkr.ecr.eu-west-2.amazonaws.com/marcopolo/gottafetchthemall:latest
		imagePullPolicy: always
        ports:
        - containerPort: 8128
